app/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.home, name='home'),
path('bolesti/<int:pk>/', views.BolestDetailView.as_view(), name='detalj'),
path('bolesti/', views.BolestListView.as_view(), name='bolesti'),
path('bolest/<int:pk>/brisi/', views.BolestDelete.as_view(), name='bolest-brisi'),
path('bolest/novi', views.BolestCreate.as_view(), name='bolest-novi'),
path("register/", views.register, name="register"),
path('registered/', views.home, name='registered'),
path('ljecnici/', views.LjecnikListView.as_view(), name='ljecnici'),
path('ljecnik/<int:pk>',views.LjecnikDetailView.as_view(), name='ljecnik-opis'),
path('ljecnik/<int:pk>/brisi/', views.LjecnikDelete.as_view(), name='ljecnik-brisi'),
path('ljecnik/novi', views.LjecnikCreate.as_view(), name='ljecnik-novi'),
path('simptom/novi', views.SimptomCreate.as_view(), name='simptom-novi'),
path('simptom2/novi', views.Simptom2Create.as_view(), name='simptom2-novi'),
path('simptom3/novi', views.Simptom3Create.as_view(), name='simptom3-novi'),
path('simptomi/', views.simptomi, name='simptomi'),
path('simptom/<int:pk>/brisi/', views.SimptomDelete.as_view(), name='simptom-brisi'),
path('simptom2/<int:pk>/brisi/', views.Simptom2Delete.as_view(), name='simptom2-brisi'),
path('simptom3/<int:pk>/brisi/', views.Simptom3Delete.as_view(), name='simptom3-brisi'),
path('bolest/<int:pk>/update', views.UpdateBolest.as_view(), name='bupdate'),
path('ljecnik/<int:pk>/update', views.UpdateLjecnik.as_view(), name='ljupdate'),
path('simptom/<int:pk>/update', views.UpdateSimptom.as_view(), name='supdate'),
path('simptom2/<int:pk>/update', views.UpdateSimptom2.as_view(), name='s2update'),
path('simptom3/<int:pk>/update', views.UpdateSimptom3.as_view(), name='s3update'),
path('pregled/<int:pk>/add/', views.PregledAdd.as_view(), name='pg'),
path('mpregled/', views.PregledKorisnik.as_view(), name='m-pregled'),
path('lpregled/', views.PregledLjecnik.as_view(), name='l-pregled'),
path('lpregled/<int:pk>/update', views.PregledUpdate.as_view(), name='lupdate'),
path('user/<int:pk>', views.UserDetail.as_view(), name='user'),

]

projekt2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Bolest(models.Model):
	naziv = models.CharField(max_length = 100)
	simptom = models.ForeignKey('Simptom', on_delete=models.SET_NULL, null=True, verbose_name = 'Prvi Simptom')
	simptom2 = models.ForeignKey('Simptom2', on_delete=models.SET_NULL, null=True, verbose_name = 'Drugi Simptom')
	simptom3 = models.ForeignKey('Simptom3', on_delete=models.SET_NULL, null=True, verbose_name = 'Treći Simptom')
	ljecnik = models.ForeignKey('Ljecnik', on_delete=models.SET_NULL, null= True, verbose_name= 'Lječnik')

	class Meta:
		verbose_name_plural = "Bolesti"

	def __str__(self):
		return self.naziv

	def get_absolute_url(self):
		return reverse('detalj', args=[str(self.id)])


class Simptom(models.Model):
	naziv = models.CharField(max_length = 100)
	class Meta:
		verbose_name_plural = "Prvi Simptomi"


	def __str__(self):
		return self.naziv
	def get_absolute_url(self):
		return reverse('simptomi')

class Simptom2(models.Model):
	naziv = models.CharField(max_length = 100)
	

	class Meta:
		verbose_name_plural = "Drugi Simptomi"


	def __str__(self):
		return self.naziv

	def get_absolute_url(self):
		return reverse('simptomi')

class Simptom3(models.Model):
	naziv = models.CharField(max_length = 100)

	class Meta:
		verbose_name_plural = "Treći Simptomi"


	def __str__(self):
		return self.naziv

	def get_absolute_url(self):
		return reverse('simptomi')

class Ljecnik(models.Model):
	ime = models.CharField(max_length= 20)
	prezime = models.CharField(max_length= 20)
	opis = models.TextField(max_length = 200)
	telefon = models.CharField(max_length= 10, blank = True)
	oib = models.CharField(max_length= 11, verbose_name = 'OIB')
	lokacija = models.CharField(max_length= 50)
	Korisnik = models.OneToOneField(User, on_delete=models.SET_NULL, null= True)

	class Meta:
		verbose_name_plural = "Lječnici"

	def __str__(self):
		return '{0}, {1}'.format(self.prezime, self.ime)
	def get_absolute_url(self):
		return reverse('ljecnik-opis', args=[str(self.id)])

class Pregled(models.Model):
    naziv = models.CharField(max_length = 100, null = True, )
    ljec = models.ForeignKey('Ljecnik', on_delete=models.CASCADE, null=True, verbose_name = 'Lječnik', blank = True) 
    dat_pregleda = models.DateField(null=True, blank=True)
    bolest = models.ForeignKey('Bolest', on_delete=models.CASCADE, null=True, blank=True, verbose_name = 'Bolest')
    use = models.ForeignKey(User, on_delete=models.CASCADE ,null=True,verbose_name = 'Korisnik' )
    vrijeme = models.TimeField(null= True, blank = True) 



    STATUS = (
        ('z', 'Zatražio pregled'),
        ('p', 'Prihvaćen pregled'),
        
        
    )

    status = models.CharField(
        max_length=1,
        choices=STATUS,
        blank=False,
        default='z',
        )

    class Meta:
        verbose_name_plural = "Pregledi"
        permissions = (('pregled', 'pregled'),)
    def __str__(self):
    	return self.naziv
        
	

app/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm

STATUS = (
            ('z', 'Zatražio pregled'),)


class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
        help_texts = {
            'username': None,
            'email': None,
        }

class LjecnikForm(forms.ModelForm):
	class Meta:
		model = Ljecnik
		fields = ['ime', 'prezime', 'opis','telefon', 'oib', 'lokacija','Korisnik']


class BolestForm(forms.ModelForm):
	class Meta:
		model = Bolest
		fields = ['naziv','simptom', 'simptom2', 'simptom3','ljecnik']

class SimptomForm(forms.ModelForm):
    class Meta:
        model = Simptom
        fields = ['naziv']

class Simptom2Form(forms.ModelForm):
    class Meta:
        model = Simptom2
        fields = ['naziv']

class Simptom3Form(forms.ModelForm):
    class Meta:
        model = Simptom3
        fields = ['naziv']

class PregledForm(forms.ModelForm):
    status = forms.ChoiceField(choices= STATUS)
    class Meta:
        model = Pregled
        
        fields = ['naziv', 'dat_pregleda', 'bolest']
        exclude = ('dat_pregleda',)
        dat_pregleda = forms.DateField(
            widget=forms.DateInput(format='%d.%m.%Y'),
            input_formats=('%d.%m.%Y'),
            label = 'Datum Pregleda'
            )

class PregledLForm(forms.ModelForm):
    class Meta:
        model = Pregled
        fields = ['dat_pregleda','vrijeme','status']
        dat_pregleda = forms.DateField(
            widget=forms.DateInput(format='%d.%m.%Y'),
            input_formats=('%d.%m.%Y'),
            label = 'Datum Pregleda'
            )

        
            
        
  

app/templates/app/base.html
  
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/main.css' %}">


    {% if title %}
        <title>Aplikacija - {{ title }}</title>
    {% else %}
        <title>Aplikacija</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home' %}">Aplikacija za prikaz bolesti po simptomima</a>
          
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
               {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{%url 'user' user.id%} ">Korisnik: {{ user.get_username }}</a>
                  {%if user.is_superuser%}
                  <a class="nav-item nav-link" href="/admin">Admin</a>
                  {%endif%}
                  <a class="nav-item nav-link" href="{% url 'logout'%}?next={{request.path}}">Odjava</a> 
              {% else %}
                   <a class="nav-item nav-link" href="{% url 'login'%}?next={{request.path}}">Prijava</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div id= "mydiv" class="col-md-8">
          {% block content %}{% endblock %}
        </div>
        <div id="mydiv2" class="col-md-4">
          
            {% if user.is_authenticated %}
            <p>
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"> <a href="{%url 'bolesti'%}">Pregled bolesti</a></li>
                <li class="list-group-item list-group-item-light"> <a href="{% url 'ljecnici'%}">Pregled lječnika</a></li>
                <li class="list-group-item list-group-item-light"> <a href="{% url 'm-pregled'%}">Moji pregledi</a></li>
                {% if user.is_staff %}
                
                
                <li class="list-group-item list-group-item-light"> <a href="{% url 'l-pregled'%}">Nepotvrđeni pregledi</a></li>
                {%endif%}
                {%if user.is_superuser%}
                <li class="list-group-item list-group-item-light"> <a href="{% url 'ljecnik-novi'%}">Unos lječnika</a></li>
                <li class="list-group-item list-group-item-light"> <a href="{% url 'bolest-novi'%}">Unos bolesti</a></li>
                <li class="list-group-item list-group-item-light"> <a href="{% url 'simptomi'%}">Lista simptoma</a></li>
                <li class="list-group-item list-group-item-light"> <a href="{% url 'simptom-novi'%}">Unos prvih simptoma</a></li>
                <li class="list-group-item list-group-item-light"> <a href="{% url 'simptom2-novi'%}">Unos drugih simptoma</a></li>
                <li class="list-group-item list-group-item-light"> <a href="{% url 'simptom3-novi'%}">Unos trećih simptoma</a></li>

                {%endif%}
              </ul>
            </p>
            {% endif %}
          </div>
        
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <script>
        $('#id_dat_pregleda').datepicker({format: 'dd.mm.yyyy'});
    </script>
    <script>
        $('#id_vrijeme').timepicker();
    </script>
    

    <script>
      // This example requires the Places library. Include the libraries=places
      // parameter when you first load the API. For example:
      // <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">

      var map;
      var service;
      var infowindow;

      function initMap() {
        

        infowindow = new google.maps.InfoWindow();

        map = new google.maps.Map(
            document.getElementById('map'), {zoom: 15});

        var request = {
          query: '{{ljecnik.lokacija}}',
          fields: ['name', 'geometry'],
        };

        service = new google.maps.places.PlacesService(map);

        service.findPlaceFromQuery(request, function(results, status) {
          if (status === google.maps.places.PlacesServiceStatus.OK) {
            for (var i = 0; i < results.length; i++) {
              createMarker(results[i]);
            }

            map.setCenter(results[0].geometry.location);
          }
        });
      }

      function createMarker(place) {
        var marker = new google.maps.Marker({
          map: map,
          position: place.geometry.location
        });

        google.maps.event.addListener(marker, 'click', function() {
          infowindow.setContent(place.name);
          infowindow.open(map, this);
        });
      }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyACegIHx2Yy6zJZNUefeaW2cRSwMsACUQI&libraries=places&callback=initMap" async defer></script>


    
</body>
</html>

app/templates/app/base1.html
  
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'app/main.css' %}">


    {% if title %}
        <title>Aplikacija- {{ title }}</title>
    {% else %}
        <title>Aplikacija</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home' %}">Aplikacija</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            

            <div class="navbar-nav">
               
                  <a class="nav-item nav-link" href="{% url 'register'%}">Registracija</a> 
              
                   
        
            
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/bolest.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <!-- <form method="post" action="" >
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
       <input type="submit" value="Submit" /> 


    </form>-->
    <form method="get" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="input-group mb-3">
  <div class="input-group-append">
    
    <button type="submit" class="btn btn-success">Nastavi</button>
</div>
</div>

  </form>


{% endblock %}

app/templates/app/bolest_detail.html
{% extends "app/base.html" %}

{% block content %}

<h1>Naziv bolesti: {{ bolest.naziv }}</h1>
<h3>Lječnik:</strong><a href="{% url 'ljecnik-opis' bolest.ljecnik.pk %}"> {{ bolest.ljecnik }}</a></h3>
<div style="margin-left:20px;margin-top:20px">
<h4>Simptomi</h4>
<p><strong>Prvi simptom:</strong> {{ bolest.simptom }}</p>
<p><strong>Drugi simptom:</strong> {{ bolest.simptom2 }}</p>
<p><strong>Treći simptom:</strong> {{ bolest.simptom3 }}</p>
</div>




{% endblock %}

app/templates/app/bolest_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <!-- <form method="post" action="" >
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
       <input type="submit" value="Submit" /> 


    </form>-->
    <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="input-group mb-3">
  <div class="input-group-append">
    
    <button type="submit" class="btn btn-success">Nastavi</button>
</div>
</div>

  </form>


{% endblock %}

app/templates/app/ljecnik_detail.html
{% extends "app/base.html" %}

{% block content %}

<h1>Lječnik: {{ ljecnik }} </h1>
<p>Telefon: {{ljecnik.telefon}} </p>
<p>OIB: {{ljecnik.oib}}</p>
<p>Lokacija: {{ljecnik.lokacija}}</p>
<p>Opis: {{ljecnik.opis}}</p>
<p><a href="{% url 'pg' ljecnik.id %}" class = "btn btn-primary" style= "position: relative; left: 0%">Zatraži pregled</a></p>

<style>
      
      #mydiv{
        padding-top: 10%;
      	padding-bottom: 300px;
      }
      #mydiv2{
      	padding-top: 10%
        
      }
      #map {
        height: 100%;
        width: 60%

      }
    
      html, body {
        height: 100%;
        
        margin: 0;
        padding : 0;
      }
    </style>

<div class =""col-md-8 id="map"></div>


{% endblock %}

app/templates/app/ljecnik_list.html
{% extends "app/base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <h1>Popis Lječnika</h1>

    {% if ljecnik_list %}
    <table class="table table-bordered">
       <thead class="thead-dark">
        <tr>
      <th scope="col">Naziv</th>
      <th scope="col">Telefon</th>
      <th scope="col">OIB</th>
      <th scope="col">Lokacija</th>

      {% if user.is_superuser %}
      <th scope="col"></th>
      <th scope="col"></th>
      {%endif%}
        </tr>
      </thead>

      {% for ljecnik in ljecnik_list %}
      <tbody>
      
      <td><a href="{{ ljecnik.get_absolute_url }}">{{ljecnik.prezime}},{{ljecnik.ime}}</a></td> 
      <td>{{ljecnik.telefon}}</td> 
      <td>{{ljecnik.oib}}</td> 
      <td>{{ljecnik.lokacija}}</td> 
      {% if user.is_superuser %}
      <td><a href="{% url 'ljupdate' ljecnik.id %}">Ažuriraj</a></td> 
      <td><a href="{% url 'ljecnik-brisi' ljecnik.id %}">Izbriši</a></td> 
      {%endif%}
      </tbody>
      {% endfor %}
      </table>

  

    {% else %}
      <p>Nema lječnika.</p>
    {% endif %}   
    {%endif%}    
{% endblock %}

app/templates/app/pregled_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <!-- <form method="post" action="" >
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
       <input type="submit" value="Submit" /> 


    </form>-->
    <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="input-group mb-3">
  <div class="input-group-append">
    
    <button type="submit" class="btn btn-success">Nastavi</button>
</div>
</div>

  </form>


{% endblock %}

app/templates/app/pregledkorisnik.html
{% extends "app/base.html" %}

{% block content %}
    <h1>Moji pregledi</h1>

    {% if pregled_list %}
    <div class="list-group">

      {% for p in pregled_list %} 
      <a class="list-group-item list-group-item-action flex-column align-items-start">
      
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{p.naziv}}</h5>
          <small>({{ p.dat_pregleda }})</small>
        </div>
        <small>({{ p.vrijeme }})</small>
      </a>
      {% endfor %}
     </div>

    {% else %}
      <p>Nema prihvaćenih pregleda.</p>
    {% endif %}       
{% endblock %}

app/templates/app/pregledljecnik.html
{% extends "app/base.html" %}

{% block content %}
    <h1>Popis Neprihvaćenih pregleda</h1>

    {% if pregled_list %}
    <table class="table table-bordered">
       <thead class="thead-dark">
        <tr>
      <th scope="col">Naziv</th>
      <th scope="col">Korisnik</th>
      <th scope="col">Boelst</th>

      {% if user.is_staff %}
      <th scope="col"></th>
      {%endif%}
        </tr>
      </thead>

      {% for p in pregled_list %}
      <tbody>
      
      <td>{{p.naziv}}</a></td> 
      <td>{{p.use}}</td>  
      <td>{{p.bolest}}</td>  
      {% if user.is_staff %}
      <td><a href="{% url 'lupdate' p.id %}">Potvrdi</a></td> 
      {%endif%}
      </tbody>
      {% endfor %}
      </table>
    {% else %}
      <p>Nema  pregleda.</p>
    {% endif %}       
{% endblock %}

app/templates/app/simptom2_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <!-- <form method="post" action="" >
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
       <input type="submit" value="Submit" /> 


    </form>-->
    <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="input-group mb-3">
  <div class="input-group-append">
    
    <button type="submit" class="btn btn-success">Nastavi</button>
</div>
</div>

  </form>


{% endblock %}

app/templates/app/simptom3_confirm_delete.html
{% extends "app/base1.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h1>Brisanje simptoma</h1>

<p>Želite li izbrisati simptom: {{ simptom3 }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <div class="input-group mb-3">
  <div class="input-group-append">
    
    <button type="submit" class="btn btn-danger">Da</button>
</div>
</div>

{% endblock %}

app/templates/app/simptom3_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <!-- <form method="post" action="" >
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
       <input type="submit" value="Submit" /> 


    </form>-->
    <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="input-group mb-3">
  <div class="input-group-append">
    
    <button type="submit" class="btn btn-success">Nastavi</button>
</div>
</div>

  </form>


{% endblock %}

app/templates/app/simptom_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <!-- <form method="post" action="" >
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
       <input type="submit" value="Submit" /> 


    </form>-->
    <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="input-group mb-3">
  <div class="input-group-append">
    
    <button type="submit" class="btn btn-success">Nastavi</button>
</div>
</div>

  </form>


{% endblock %}